### ISSUE TITLE
addRemoteTrack() not working in Firefox

### ISSUE THREAD

**Issue by nico-ramos** [millicast/millicast-sdk#168]
**Version affected**
0.1.29

**Describe the bug**
`millicastView.addRemoteTrack()` doesn't work in Firefox. It throws:
`Uncaught (in promise) DOMException: Answer has extmap http://www.webrtc.org/experiments/rtp-hdrext/abs-capture-time at level 0 that was not present in offer.`

**Environment (please complete the following information):**
 - Browser Firefox

**Comment by murillo128** [comment]
The issue is that we are only modifying the local sdp for adding the header extensions and codecs on the initial offer.

We would need to add a  `updateAbsoluteCaptureTime` and `updateDependencyDescriptor` method that first look for the current id used for the extension in the current sdp. 

Then for each video section, check if the extension is already present for that media section and if not add it with the same id as the one present in the other sections.

We should then add the method to update the sdp when we do the renegotiation. 

We need to also do the same with multiopus.
